doctrine:
  orm:
    # ...
    entity_managers:
      default:
        dql:
          string_functions:
            GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
            IFNULL: DoctrineExtensions\Query\Mysql\IfNull
