version: '2'
services:
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: hpo
        container_name: healthpro-mysql
        hostname: healthpro-mysql
        platform: linux/x86_64
        image: mysql:8.0.37
        ports:
            - "53306:3306"
        volumes:
            - healthpro-mysql-data:/var/lib/mysql

    web:
        environment:
            MYSQL_HOST: healthpro-mysql
            MYSQL_DATABASE: hpo
            MYSQL_USER: root
            MYSQL_PASSWORD: ''
        build: .
        container_name: healthpro-web
        hostname: healthpro-web
        links:
            - mysql
        ports:
            - "8080:8080"
        volumes:
            - .:/app:delegated

volumes:
    healthpro-mysql-data:
