monolog:
    channels: [deprecation]
    handlers:
        filter_syslog_errors:
            type: fingers_crossed
            handler: syslog_handler
            action_level: info
            excluded_http_codes: [404]
            channels: ["!deprecation"]
        filter_stackdriver_errors:
            type: fingers_crossed
            handler: stackdriver_handler
            action_level: info
            excluded_http_codes: [404]
            channels: ["!deprecation"]
        syslog_handler:
            type: syslog
            ident: false
            facility: !php/const LOG_USER
            level: info
        stackdriver_handler:
            type: service
            id: App\Service\StackdriverHandler
