framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/../web/build/manifest.json'
        # Switch back to '%kernel.project_dir%/public/build/manifest.json' after fully migrating to Symfony
