index:
    path: /
    controller: App\Controller\DefaultController::index

# Legacy Silex Routes

home:
    path: /

logout:
    path: /logout

selectSite:
    path: /site/select

evaluation:
    path: /participant/{participantId}/measurements/{evalId}
    defaults: { evalId: null }

evaluation_modify:
    path: /participant/{participantId}/measurements/{evalId}/modify/{type}

evaluationBloodDonorCheck:
    path: /participant/{participantId}/measurements/blood/donor/check

clientTimeout:
    path: /client-timeout

keepAlive:
    path: /keepalive

agreeUsage:
    path: /agree

hideTZWarning:
    path: /hide-tz-warning

patientStatus:
    path: /participant/{participantId}/patient/status/{patientStatusId}
