index:
    path: /
    controller: App\Controller\DefaultController::index

# Legacy Silex Routes

home:
    path: /

selectSite:
    path: /site/select

evaluation:
    path: /participant/{participantId}/measurements/{evalId}
    defaults: { evalId: null }

evaluation_modify:
    path: /participant/{participantId}/measurements/{evalId}/modify/{type}

evaluationBloodDonorCheck:
    path: /participant/{participantId}/measurements/blood/donor/check
