index:
    path: /
    controller: App\Controller\DefaultController::index

# Legacy Silex Routes

home:
    path: /

logout:
    path: /logout

selectSite:
    path: /site/select

participants:
    path: /participants

orders:
    path: /orders

evaluation:
    path: /participant/{participantId}/measurements/{evalId}
    defaults:
      - evalId: null

evaluation_modify:
    path: /participant/{participantId}/measurements/{evalId}/modify/{type}

workqueue_index:
    path: /workqueue

dashboard_home:
    path: /dashboard

biobank_home:
    path: /biobank

clientTimeout:
    path: /client-timeout

keepAlive:
    path: /keepalive

agreeUsage:
    path: /agree

hideTZWarning:
    path: /hide-tz-warning

participant:
    path: /participant/{id}
