index:
    path: /
    controller: App\Controller\DefaultController::index

# Legacy Silex Routes

home:
    path: /

logout:
    path: /logout

help_home:
    path: /help

help_videos:
    path: /help/videos

help_faq:
    path: /help/faq

help_sop:
    path: /help/sop

selectSite:
    path: /site/select

participants:
    path: /participants

orders:
    path: /orders

review_today:
    path: /review

review_orders:
    path: /review/orders

review_measurements:
    path: /review/measurements

review_ordersRecentModify:
    path: /review/orders/recent/modify

review_measurementsRecentModify:
    path: /review/measurements/recent/modify

workqueue_index:
    path: /workqueue

problem_reports:
    path: /problem/reports

admin_home:
    path: /admin

dashboard_home:
    path: /dashboard

biobank_home:
    path: /biobank

clientTimeout:
    path: /client-timeout

keepAlive:
    path: /keepalive

agreeUsage:
    path: /agree

hideTZWarning:
    path: /hide-tz-warning

participant:
    path: /participant/{id}
