index:
    path: /
    controller: App\Controller\DefaultController::index

# Legacy Silex Routes

home:
    path: /

logout:
    path: /logout

selectSite:
    path: /site/select

participants:
    path: /participants

orders:
    path: /orders

review_today:
    path: /review

workqueue_index:
    path: /workqueue

problem_reports:
    path: /problem/reports

admin_home:
    path: /admin

dashboard_home:
    path: /dashboard

biobank_home:
    path: /biobank

clientTimeout:
    path: /client-timeout

keepAlive:
    path: /keepalive

agreeUsage:
    path: /agree

hideTZWarning:
    path: /hide-tz-warning
