monolog:
    handlers:
        syslog_handler:
            type: syslog
            ident: false
            facility: !php/const LOG_USER
            level: info
        service:
            type: service
            id: App\Service\StackdriverHandler
