<?php
/**
 * This file routes requests to either the Symfony or Silex front controller.
 *
 * Expected phases:
 * 1) Everything goes to Silex unless you're in < stable and the path starts with /s/
 * 2) [CURRENT] Everything goes to Silex unless the path starts with /s/
 * 3) Everything goes to Symfony unless the path starts with /x/
 * 4) Everything goes to Symfony
 */


/**
 * In and after phase 2, we can move the autoload and instantiation of HpoApplication
 * back to the silex-index.php and remove the $allowSymfony check
 */

require_once __DIR__ . '/../vendor/autoload.php';

use Pmi\Application\HpoApplication;

$app = new HpoApplication();

/**
 * Requests that include the entrypoint path lead to unexpected paths generated by the
 * Symfony routing component due to the way GAE routes requests. To avoid this, we exit
 * with an early 404 response.
 */
if (strpos($_SERVER['REQUEST_URI'], 'index.php') !== false) {
    header('HTTP/1.1 404 Not Found');
    exit('Not Found');
}

$path = @parse_url($_SERVER['REQUEST_URI'])['path'];
if (preg_match("/^\/s(\/|$)/", $path)) {
    require '../symfony/public/index.php';
} else {
    require 'silex-index.php';
}
