<?php

/**
 * Requests that include the entrypoint path lead to unexpected paths generated by the
 * Symfony routing component due to the way GAE routes requests. To avoid this, we exit
 * with an early 404 response.
 */
if (strpos($_SERVER['REQUEST_URI'], 'index.php') !== false) {
    header('HTTP/1.1 404 Not Found');
    exit('Not Found');
}

require '../public/index.php';
